"""enum subscription status

Revision ID: 131a23e2cc99
Revises: 60d36be2e019
Create Date: 2023-01-10 00:00:11.440186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131a23e2cc99'
down_revision = '60d36be2e019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_subscription', sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe_subscription', 'last_modified')
    # ### end Alembic commands ###
