"""Add properties to TyneUser

Revision ID: 15cd6fadf21b
Revises: b6a98131b14f
Create Date: 2024-03-25 12:03:43.408457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15cd6fadf21b'
down_revision = 'b6a98131b14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tyne_user', sa.Column('properties', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tyne_user', 'properties')
    # ### end Alembic commands ###
