"""User view state

Revision ID: 192ef8ac8f9f
Revises: 81555406c529
Create Date: 2024-06-17 15:15:46.975318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192ef8ac8f9f'
down_revision = '81555406c529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('view_state', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'view_state')
    # ### end Alembic commands ###
