"""Published property

Revision ID: 1d0b1fe3398c
Revises: 5b1f48fc808e
Create Date: 2022-02-23 15:08:44.390880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0b1fe3398c'
down_revision = '5b1f48fc808e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tyne', sa.Column('published', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_tyne_published'), 'tyne', ['published'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tyne_published'), table_name='tyne')
    op.drop_column('tyne', 'published')
    # ### end Alembic commands ###
