"""rename subscription_id

Revision ID: 2631ed812fa3
Revises: cc52383c2b2f
Create Date: 2023-01-05 23:46:47.503715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2631ed812fa3'
down_revision = 'cc52383c2b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('subscription_id', sa.Text(), nullable=True))
    op.drop_constraint('organization_subscription_fkey', 'organization', type_='foreignkey')
    op.create_foreign_key(None, 'organization', 'stripe_subscription', ['subscription_id'], ['id'])
    op.drop_column('organization', 'subscription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('subscription', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.create_foreign_key('organization_subscription_fkey', 'organization', 'stripe_subscription', ['subscription'], ['id'])
    op.drop_column('organization', 'subscription_id')
    # ### end Alembic commands ###
