"""Add TyneUser table with last_opened

Revision ID: 29e223b70931
Revises: 906ffe3312f9
Create Date: 2023-07-21 12:00:09.475249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e223b70931'
down_revision = '906ffe3312f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tyne_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tyne_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_opened', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tyne_id'], ['tyne.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tyne_user_tyne_id'), 'tyne_user', ['tyne_id'], unique=False)
    op.create_index(op.f('ix_tyne_user_user_id'), 'tyne_user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tyne_user_user_id'), table_name='tyne_user')
    op.drop_index(op.f('ix_tyne_user_tyne_id'), table_name='tyne_user')
    op.drop_table('tyne_user')
    # ### end Alembic commands ###
