"""org_service_index

Revision ID: 2a482ada0805
Revises: c632ee7ded72
Create Date: 2024-04-19 17:04:38.091029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a482ada0805'
down_revision = 'c632ee7ded72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('org_service_name_idx', 'api_quota', ['organization_id', 'service_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('org_service_name_idx', table_name='api_quota')
    # ### end Alembic commands ###
