"""add cascade deletes

Revision ID: 2e3616e59bda
Revises: cb8f9bcbdea1
Create Date: 2023-07-31 16:11:37.117280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3616e59bda'
down_revision = 'cb8f9bcbdea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tyne_user_tyne_id_fkey', 'tyne_user', type_='foreignkey')
    op.drop_constraint('tyne_user_user_id_fkey', 'tyne_user', type_='foreignkey')
    op.create_foreign_key(None, 'tyne_user', 'tyne', ['tyne_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tyne_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tyne_user', type_='foreignkey')
    op.drop_constraint(None, 'tyne_user', type_='foreignkey')
    op.create_foreign_key('tyne_user_user_id_fkey', 'tyne_user', 'user', ['user_id'], ['id'])
    op.create_foreign_key('tyne_user_tyne_id_fkey', 'tyne_user', 'tyne', ['tyne_id'], ['id'])
    # ### end Alembic commands ###
