"""Add version

Revision ID: 3180fb7e55f9
Revises: 1d0b1fe3398c
Create Date: 2022-04-04 12:54:40.865125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3180fb7e55f9'
down_revision = '1d0b1fe3398c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tyne', sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tyne', 'version')
    # ### end Alembic commands ###
