"""Screenshot Url for Gallery

Revision ID: 32fd88aa1710
Revises: 3ee51b781e37
Create Date: 2022-08-02 17:57:55.098283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32fd88aa1710'
down_revision = '3ee51b781e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tyne', sa.Column('screenshot_url', sa.Text(), nullable=True))
    op.drop_column('tyne', 'screenshot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tyne', sa.Column('screenshot', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('tyne', 'screenshot_url')
    # ### end Alembic commands ###
