"""Gallery and screenshot

Revision ID: 3ee51b781e37
Revises: e071ce6ce63f
Create Date: 2022-07-25 19:51:39.213991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee51b781e37'
down_revision = 'e071ce6ce63f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tyne', sa.Column('screenshot', sa.LargeBinary(), nullable=True))
    op.add_column('tyne', sa.Column('in_gallery', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.create_index(op.f('ix_tyne_in_gallery'), 'tyne', ['in_gallery'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tyne_in_gallery'), table_name='tyne')
    op.drop_column('tyne', 'in_gallery')
    op.drop_column('tyne', 'screenshot')
    # ### end Alembic commands ###
