"""waitlist update

Revision ID: 417e02512841
Revises: e1b10ea6ca32
Create Date: 2022-11-02 11:40:19.361127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417e02512841'
down_revision = 'e1b10ea6ca32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_waitlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('invite_sent_at', sa.DateTime(), nullable=True),
    sa.Column('invite_token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_waitlist_email'), 'email_waitlist', ['email'], unique=True)
    op.create_index(op.f('ix_email_waitlist_invite_token'), 'email_waitlist', ['invite_token'], unique=False)
    op.add_column('waitlist', sa.Column('self_removed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waitlist', 'self_removed')
    op.drop_index(op.f('ix_email_waitlist_invite_token'), table_name='email_waitlist')
    op.drop_index(op.f('ix_email_waitlist_email'), table_name='email_waitlist')
    op.drop_table('email_waitlist')
    # ### end Alembic commands ###
