"""n_row and n_col in sheet

Revision ID: 4dea09f8f4e3
Revises: 5bbc598b8a11
Create Date: 2022-05-15 15:19:35.798066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dea09f8f4e3'
down_revision = '5bbc598b8a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheet', sa.Column('n_rows', sa.Integer(), nullable=True))
    op.add_column('sheet', sa.Column('n_cols', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheet', 'n_cols')
    op.drop_column('sheet', 'n_rows')
    # ### end Alembic commands ###
