"""Add API Quota table

Revision ID: 502b1d8bdff3
Revises: f18e3e3e6d9f
Create Date: 2023-07-10 14:08:05.037369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502b1d8bdff3'
down_revision = 'f18e3e3e6d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_quota',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.Text(), nullable=False),
    sa.Column('usage', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service_name', name='_user_service_name_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_quota')
    # ### end Alembic commands ###
