"""Add secrets table

Revision ID: 5bbc598b8a11
Revises: 3180fb7e55f9
Create Date: 2022-05-05 12:12:18.987925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bbc598b8a11'
down_revision = '3180fb7e55f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tyne_secrets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tyne_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tyne_id'], ['tyne.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tyne_id', 'user_id', name='_tyne_id_user_id_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tyne_secrets')
    # ### end Alembic commands ###
