"""Add OrgInvite Table

Revision ID: 5fecc1140297
Revises: 5af8aaaf7423
Create Date: 2022-12-19 13:36:16.359787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fecc1140297'
down_revision = '5af8aaaf7423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_invite',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('invite_token', sa.Text(), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_invite')
    # ### end Alembic commands ###
