"""Add notebook id and name

Revision ID: 61a97fc94052
Revises: 7f81a5822b6a
Create Date: 2022-05-27 17:23:17.799458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a97fc94052'
down_revision = '7f81a5822b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebook', sa.Column('notebook_id', sa.Integer(), nullable=True))
    op.add_column('notebook', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebook', 'name')
    op.drop_column('notebook', 'notebook_id')
    # ### end Alembic commands ###
