"""Keep next sheet id

Revision ID: 721f35ed8d63
Revises: 61a97fc94052
Create Date: 2022-06-30 14:08:56.980258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721f35ed8d63'
down_revision = '61a97fc94052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tyne', sa.Column('next_sheet_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tyne', 'next_sheet_id')
    # ### end Alembic commands ###
