"""Add sheet id and name

Revision ID: 7f81a5822b6a
Revises: 4dea09f8f4e3
Create Date: 2022-05-27 13:31:07.110355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f81a5822b6a'
down_revision = '4dea09f8f4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheet', sa.Column('sheet_id', sa.Integer(), nullable=True))
    op.add_column('sheet', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheet', 'name')
    op.drop_column('sheet', 'sheet_id')
    # ### end Alembic commands ###
