"""Tyne properties

Revision ID: 8c6249e9aac2
Revises: 32fd88aa1710
Create Date: 2022-09-06 16:46:51.159058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6249e9aac2'
down_revision = '32fd88aa1710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tyne', sa.Column('properties', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tyne', 'properties')
    # ### end Alembic commands ###
