"""Add indexes to API quota table

Revision ID: 906ffe3312f9
Revises: 502b1d8bdff3
Create Date: 2023-07-11 09:23:00.748448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906ffe3312f9'
down_revision = '502b1d8bdff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_service_name_uc', 'api_quota', type_='unique')
    op.create_index(op.f('ix_api_quota_user_id'), 'api_quota', ['user_id'], unique=False)
    op.create_index('user_service_name_idx', 'api_quota', ['user_id', 'service_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_service_name_idx', table_name='api_quota')
    op.drop_index(op.f('ix_api_quota_user_id'), table_name='api_quota')
    op.create_unique_constraint('_user_service_name_uc', 'api_quota', ['user_id', 'service_name'])
    # ### end Alembic commands ###
