"""Autojoin field

Revision ID: 972ce7d48172
Revises: cd9f7553ec38
Create Date: 2023-08-08 00:58:33.985128

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "972ce7d48172"
down_revision = "cd9f7553ec38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column(
            "allow_autojoin",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
    )
    op.drop_constraint("user_org_user_id_fkey", "user_org", type_="foreignkey")
    op.create_foreign_key(
        None, "user_org", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_org", type_="foreignkey")
    op.create_foreign_key(
        "user_org_user_id_fkey", "user_org", "user", ["user_id"], ["id"]
    )
    op.drop_column("organization", "allow_autojoin")
    # ### end Alembic commands ###
