"""Make has_tick not null

Revision ID: 9c195da7a54b
Revises: c4bbd9b25fb5
Create Date: 2023-01-31 10:55:48.399542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c195da7a54b'
down_revision = 'c4bbd9b25fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tyne', 'has_tick',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tyne', 'has_tick',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
