"""Add next_tick to tyne

Revision ID: ab07bc6b324b
Revises: 9c195da7a54b
Create Date: 2023-02-10 20:44:43.602335

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ab07bc6b324b'
down_revision = '9c195da7a54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tyne', sa.Column('next_tick', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tyne_next_tick'), 'tyne', ['next_tick'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tyne_next_tick'), table_name='tyne')
    op.drop_column('tyne', 'next_tick')
    # ### end Alembic commands ###
