"""add linked gsheets

Revision ID: add549685881
Revises: 0e2c7159a2c7
Create Date: 2023-08-25 13:11:23.808708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add549685881'
down_revision = '0e2c7159a2c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_sheet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sheet_id', sa.Text(), nullable=False),
    sa.Column('tyne_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tyne_id'], ['tyne.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_sheet_sheet_id'), 'google_sheet', ['sheet_id'], unique=True)
    op.create_index(op.f('ix_google_sheet_tyne_id'), 'google_sheet', ['tyne_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_sheet_tyne_id'), table_name='google_sheet')
    op.drop_index(op.f('ix_google_sheet_sheet_id'), table_name='google_sheet')
    op.drop_table('google_sheet')
    # ### end Alembic commands ###
