"""Use hash for cache index

Revision ID: b6a98131b14f
Revises: 6f56f6bd485d
Create Date: 2024-01-12 18:39:50.266198

"""
import hashlib

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b6a98131b14f"
down_revision = "6f56f6bd485d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "function_call_cache",
        sa.Column("combined_hash", sa.String(length=64), nullable=True),
    )
    op.drop_index("idx_tyne_code_expression", table_name="function_call_cache")
    op.create_index(
        "idx_tyne_combined_hash",
        "function_call_cache",
        ["tyne_id", "combined_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_function_call_cache_combined_hash"),
        "function_call_cache",
        ["combined_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_function_call_cache_combined_hash"), table_name="function_call_cache"
    )
    op.drop_index("idx_tyne_combined_hash", table_name="function_call_cache")
    op.create_index(
        "idx_tyne_code_expression",
        "function_call_cache",
        ["tyne_id", "code_panel", "expression"],
        unique=False,
    )
    op.drop_column("function_call_cache", "combined_hash")
    # ### end Alembic commands ###
