"""tyne linked api keys

Revision ID: bd5de78534f0
Revises: 81555406c529
Create Date: 2024-06-17 23:31:51.967284

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bd5de78534f0"
down_revision = "81555406c529"
branch_labels = None
depends_on = None


def upgrade():
    # Wipe all data from api_key table; Existing rows cause issues with null constraint.
    op.execute("DELETE FROM api_key")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_key", sa.Column("tyne_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_api_key_tyne_id"), "api_key", ["tyne_id"], unique=False)
    op.create_foreign_key(None, "api_key", "tyne", ["tyne_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "api_key", type_="foreignkey")
    op.drop_index(op.f("ix_api_key_tyne_id"), table_name="api_key")
    op.drop_column("api_key", "tyne_id")
    # ### end Alembic commands ###
