"""Add google workspace user table

Revision ID: bf749e7c4f30
Revises: 56224dbeb951
Create Date: 2024-05-29 12:16:51.953331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf749e7c4f30'
down_revision = '56224dbeb951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_workspace_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_workspace_user_email'), 'google_workspace_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_workspace_user_email'), table_name='google_workspace_user')
    op.drop_table('google_workspace_user')
    # ### end Alembic commands ###
