"""organization_quota

Revision ID: c632ee7ded72
Revises: 15cd6fadf21b
Create Date: 2024-04-18 15:38:33.264719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c632ee7ded72'
down_revision = '15cd6fadf21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_quota', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.alter_column('api_quota', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_api_quota_organization_id'), 'api_quota', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'api_quota', 'organization', ['organization_id'], ['id'])
    op.add_column('organization', sa.Column('trial_end', sa.DateTime(), nullable=True))
    op.drop_constraint('organization_tyne_owner_id_fkey', 'organization', type_='foreignkey')
    op.drop_column('organization', 'allow_autojoin')
    op.drop_column('organization', 'tyne_owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('tyne_owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('organization', sa.Column('allow_autojoin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('organization_tyne_owner_id_fkey', 'organization', 'tyne_owner', ['tyne_owner_id'], ['id'])
    op.drop_column('organization', 'trial_end')
    op.drop_constraint(None, 'api_quota', type_='foreignkey')
    op.drop_index(op.f('ix_api_quota_organization_id'), table_name='api_quota')
    op.alter_column('api_quota', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('api_quota', 'organization_id')
    # ### end Alembic commands ###
