"""Add organization share

Revision ID: c81bfb13e945
Revises: 29e223b70931
Create Date: 2023-07-24 23:47:44.679517

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "c81bfb13e945"
down_revision = "29e223b70931"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "organization_share",
        sa.Column("tyne_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "access_level",
            postgresql.ENUM(
                "pending", "accepted", "canceled", name="accesslevel", create_type=False
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tyne_id"],
            ["tyne.id"],
        ),
        sa.PrimaryKeyConstraint("tyne_id", "organization_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization_share")
    # ### end Alembic commands ###
