"""First pass stripe tables

Revision ID: cc52383c2b2f
Revises: 5d7e02d2a6dd
Create Date: 2023-01-05 17:14:14.631954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc52383c2b2f'
down_revision = '5d7e02d2a6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_user',
    sa.Column('id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_subscription',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('stripe_user_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stripe_user_id'], ['stripe_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organization', sa.Column('subscription', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'organization', 'stripe_subscription', ['subscription'], ['id'])
    op.add_column('user', sa.Column('stripe_id', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'user', 'stripe_user', ['stripe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'stripe_id')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'subscription')
    op.drop_table('stripe_subscription')
    op.drop_table('stripe_user')
    # ### end Alembic commands ###
