"""Organization cascade delete

Revision ID: cd9f7553ec38
Revises: a412db8068d2
Create Date: 2023-08-03 14:56:29.363276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9f7553ec38'
down_revision = 'a412db8068d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organization_share_tyne_id_fkey', 'organization_share', type_='foreignkey')
    op.drop_constraint('organization_share_organization_id_fkey', 'organization_share', type_='foreignkey')
    op.create_foreign_key(None, 'organization_share', 'tyne', ['tyne_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'organization_share', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_share', type_='foreignkey')
    op.drop_constraint(None, 'organization_share', type_='foreignkey')
    op.create_foreign_key('organization_share_organization_id_fkey', 'organization_share', 'organization', ['organization_id'], ['id'])
    op.create_foreign_key('organization_share_tyne_id_fkey', 'organization_share', 'tyne', ['tyne_id'], ['id'])
    # ### end Alembic commands ###
