"""Add environment variables

Revision ID: d17ce62169bc
Revises: 56224dbeb951
Create Date: 2024-05-29 14:19:18.762189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17ce62169bc'
down_revision = '56224dbeb951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tyne', sa.Column('environment_variables', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tyne', 'environment_variables')
    # ### end Alembic commands ###
