"""Add datetime to org share

Revision ID: d55c788546b3
Revises: 23ef743bdf52
Create Date: 2022-12-20 20:37:31.667760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55c788546b3'
down_revision = '23ef743bdf52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_invite', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('org_invite', sa.Column('claimed', sa.DateTime(), nullable=True))
    op.drop_column('org_invite', 'is_claimed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_invite', sa.Column('is_claimed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('org_invite', 'claimed')
    op.drop_column('org_invite', 'created')
    # ### end Alembic commands ###
