"""user subscription id

Revision ID: e5885f631be1
Revises: 16fa9cc723be
Create Date: 2023-04-17 13:22:58.778798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5885f631be1'
down_revision = '16fa9cc723be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_subscription_id', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'user', ['stripe_subscription_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'stripe_subscription_id')
    # ### end Alembic commands ###
