"""last_reset_api

Revision ID: f5f16bdcdb55
Revises: bf749e7c4f30
Create Date: 2024-06-04 14:10:15.702176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f16bdcdb55'
down_revision = 'bf749e7c4f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_quota', sa.Column('last_reset', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_quota', 'last_reset')
    # ### end Alembic commands ###
