"""Add role to org share

Revision ID: fd970b6ed127
Revises: d55c788546b3
Create Date: 2022-12-20 20:40:50.329162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd970b6ed127'
down_revision = 'd55c788546b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_invite', sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'GUEST', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_invite', 'role')
    # ### end Alembic commands ###
